# type definitions
from typing import Protocol


class Presenter(Protocol):
    def run(self) -> None: ...
    def set_target_ip(self, target_ip: str) -> None: ...
    def pull_media(self) -> None: ...
    def get_bank(self, bank: int | None) -> None: ...
    def show_status(self, msg: str) -> None: ...
    def import_csv(self, file_path: str) -> None: ...
